apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: team-backend-api-morriz-local
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:morriz-local-*
spec:
  releaseName: team-backend-api-morriz-local
  chart:
    git: git@github.com:Morriz/mostack
    path: charts/api
    ref: master
  valueFileSecrets:
  - name: api.morriz-local-values
  values: {}