apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: dev
  labels:
    app: api
    release: team-frontend-api-dev
    prometheus: team-frontend-prometheus
  name: team-frontend-api
spec:
  jobLabel: team-frontend-api-dev
  namespace: dev
  selector:
    matchLabels:
      app: api
      release: team-frontend-api-dev
  namespaceSelector:
    matchNames:
    - team-frontend
  endpoints:
  - port: http
    interval: 30s
