apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-morriz-local-values
  namespace: dev
spec:
  encryptedData:
    values.yaml: AgCfnoUZbxAMZZkYYgVLh1DoXoPJDVc1VF3PGsdiERgocQGAoEy60C5cx1m1iSWbz+dENjFmSv72Y9igcAOCaYRdlA/pi+gdMURtvoN726F63u6Lnwevo3NhzJ/stHxIPe+AFxBHNL+gbzTZHktvQOegGdRJ1/pWsJ3MrANcBKB5lGgX4zbXWCx7FNb/lfBrmfsz2W6aJR28dpGTgbwtZG/4ibt39i0O8JNAobEmF9JMHM0zPhwgqsPpChO2uwdPcPkalprb+CyjT9ewWFkWRF0GhWPwjzWw7dpyI2Nqjk7hU+LLMwwtwoqeeORNnIE0qaGboHUfkECvdDqPB1ZuXphiPKNSQITWVi0S1qC7SWtQBEw9nthWLMJEqF7kM1sBj33e3cXk8NFHirO9SEgw7g0k+r6KENT3CXF6TAfJTnvfbCtwLwwiEXpQswKBI7GZ9cGW5oPkJ3s3OtWxCTyaCJlpx7/YKgDDWHFgE4aLBFoBIk51JfDXuoxZDofzl3jtHaoWQH5DpOJGwcPOzn1EUpWvE4hrWowHkPwqBsJC5SHGXIpIe2g49jPNb4br+Yfsm1f/epuPtIOyfenVuY1bLnJ6h4XgbBMcIhCjthauAzlIuy24em/ynY4hocAcUnC9rG0fseR+vRxV69Xy5PiJyOMnIaDe5zRHQC2Yl16BFb7iqkvUCW7FwoHGi+OSx879qE2NoSN1zw6hZRP+0ajFyVKvuExVGwkiBukHKPoTIsfvuJa7PQb6rDvg09D+lMdBwsvRd+ec7mHHdxUMvYBZxWvK6JDLkBwb2B4rcYAqz5bJyYgqZM9mbHBYe1SpG/C1hnGMkt5SVh9JnulMkWitKDSlPz3fQOBX6OFa3vv7QxgWcd5XtiyaSyzIKrT07FrccON02JCkL1bEprxYNUPzEjG7ig8avLkT7S5sefR8TViivcWQKu9BfQWvOSaf1Jpa95W+J6CMqhUjd7pE+k/ik305sVJCryypmAON9neQI8c6iJZUiZFOmFwyNNcJjtV84T+q

