apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-morriz-local-values
  namespace: dev
spec:
  encryptedData:
    values.yaml: AgBgVh3PAqKJa54B8UEDZTJxt4znRW3WXXXmLfe9PYsK/nUw4Xq0fNe4Z3XpvCvfocE+UzDLFAnS+Mol/O+i/0mw3/Eqi/d5/lcAx8i82gbzgDWy9sAHBCB7CDvu9+ZnQDzJ9R6ETDCumyrJBB9ew8rbvOIyCVw1dY9L5lCYERIYfitOnqwbhA4+4toAiSO5i/uTVihcCyOBKC+vkP2g20ZxcovJvEWIikdYzGPLjpkjK649Oz5L8XH14UwjB3WG8uSN4RYv8lpQC68vJPWQR3VkjfAyDYTgYTaqHkpOowFkwf7MIFCtlZeOPrmN5iGqJQb1BZMLdtoKjkSv9VTT31YQ4MMEVMgq+U672A/UAibs2+MkKseDtBH1DKBXLEbMjxXoVuD0Cz0qkpaTtdle32b1au8I9b2XKzd2uFvBC23o0dkQMhGNhj1bt+KvNJngnjbvh2J3KiekkSRsrGz9hQSrixBWTw5tbP65LX7y+AbUNDtv/MYvsc6iRwrpdx2mwKzORsxNYNAyGE+1XqR+M9W8MU04QWTmN/dBUFrciyih02o/q1H4KXmyQwGSfk4vykNxGNwADZFaf3zFqaLi6fQ3XJ4NbDNDcf3y7JVtFurKAHp+hPJXxzuqW63LESYGoRlpgkkmV4db+/eFhse+KwhzgOg6qFoMxUbZKhgxGaIH5H7JfDYP7X+ZyeQ0Cb25DqU5akYipbqORJLtSXYvy42d4WhSh/6fIZ49D6PcDJCLOUff0NmSGUHtNzVDlWtw3m7eDdsZG5pzgY8YEoLO/MSR1FRkIIs1xWCqqlAc0kB/tCMVHG8+wIOQRVM9DIjZjr6tc0BxOU6FId0qL4lGyKlShJfgG7Ez/xWIgRmDXBn1LePxszaAhLVfZeXtYsY4wCL/J9i4JieFTXqODwCnQKqCIkbO8lO86nUvYVSx+78SWgNjOzrppSrVBZMsyXD8mHax0o33M059nbObzmNoEOYrH03onZrxD891ejpF8fvFT6uSs3acGGSfBomDQ6H9Lagi

