apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api.morriz-local-secrets
  namespace: dev
spec:
  encryptedData:
    values.yaml: AgAOqknqTqGBpBtXPnYml7lLrMZrSFINU8knddHTk9PaZPLCDOmrIMEKILOc+2cVuK89fygP8YAAJCxZbmxikpu1IIyGowe7y+mK97x0eSbq5uLPdSGtRPigWgAvf069iTVYtQxvQciK8Ygd8+3L03++mS2Q7xcwwJmVEdG7eplOhS0hfkRrlm+bEpKLAI82luq6hjrkCkEWSei7WYyhhresrWFsQOwTEcsL5y0pqxnbxkl3x5BHA5m9uOwCjhBPjhzbNtBYVoMOyDOD1iIx6L+CARU7rx0AHuyKM+kOzkAlSe/N/4ft51viV3VkTLR1rDUmDrm1Q+3TgFbR80Wk248S9rrmmHvVJs1sZVOBZtXUaqJzSmjGsxRWOAEQzxC2vpVd7aosNV4UeanrGsLoD+TbRdHmb8PXVWvV16mHiILIunIYKvNFDTxx5TjJccg3N9cZYttcIpPOTDxy7UL+DnYrVW8TfS0fe6EjqP2j3L+Qtc7dGn0uYRkOYBKlpeApUF3VdfUomK+0IzwAxD3vx6hFMuD68kR3TDx4Q6mbJUZg7x9xnd6JBJJTlgh1O1Y1NWxuKikoPfzX5aI+0I05tqXrnfwgiSiP+72uAOI5FuuzaylzsPbtqoi0XraaL1yuP4vJhV6+YYhJxLqZG89l9NpM0tx8pp3TWqzupWf7Ns0/lzyr9WTjfzBpomyF+YlGQd7YBx6ypigA8vBX/B0A+zJG5RXCYKpHGpb6qsKkOlpBYQYWnhZC6ADFICWDu0Jq1vcmn91wYe76pRh4pvEXObUZhGaLM5XKYbnUKzNf7mXeV+IUqyI40ht4tFRKj2pCCgwFPJVA54hYT9yENP1JPHDzGOXnbRFkw18+RWMJClI6zfuEWLujEb+2hc9vvkWe3vKHUciGj/lbVDK53F4wZsvMiaYANXWRr4QRuqRKbFiYdugxC+t6Yc8WlX6QACCxkNT3qYgKT8C8Urkh5g5KIa87jRZUZTU3z3uA1qGuOxxSDVVYVAuFT5NCQgzMabbwFQ==

