apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: kube-prometheus
  namespace: monitoring
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0.1
spec:
  namespace: monitoring
  chartGitPath: kube-prometheus
  releaseName: kube-prometheus
  values:
    deployCoreDNS: true
    deployKubeDNS: false
    deployKubeEtcd: false
    global:
      rbacEnable: true
    prometheus:
      # prometheusLabelValue: prometheus
      resources:
        requests:
          memory: 400Mi
      # externalUrl: https://prometheus.dev.idiotz.nl
      externalUrl: http://127.0.0.1:9090
      secrets:
        - drone-auth
    alertmanager:
      # prometheusLabelValue: prometheus
      config:
        global:
          slack_api_url: https://hooks.slack.com/services/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
        route:
          receiver: default-receiver
          repeat_interval: 3h
          routes:
            - match:
                alertname: DeadMansSwitch
              repeat_interval: 5m
              receiver: deadmansswitch
        receivers:
          - name: deadmansswitch
          - name: default-receiver
            slack_configs:
              - channel: "#devops"
                send_resolved: true
      # to have clickable links in the gui:          
      # externalUrl: https://alertmanager.dev.idiotz.nl
      externalUrl: http://127.0.0.1:9093
    grafana:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          kubernetes.io/tls-acme: "true"
          ingress.kubernetes.io/rewrite-target: /
          ingress.kubernetes.io/ssl-redirect: "true"
        hosts:
          - grafana.dev.idiotz.nl
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.dev.idiotz.nl
      adminPassword: jaja

    # fix for wrong selector:
    exporter-kube-controller-manager:
      serviceSelectorLabelKey: component
      k8sCoreComponentsNamespace: kube-system
    exporter-kube-scheduler:
      serviceSelectorLabelKey: component
      k8sCoreComponentsNamespace: kube-system
    exporter-kube-etcd:
      serviceSelectorLabelKey: component
      serviceSelectorLabelValue: etcd
