apiVersion: v1
kind: Secret
metadata:
  name: drone-auth
  namespace: monitoring
data:
  secret: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjBaWGgwSWpvaVRXOXljbWw2SWl3aWRIbHdaU0k2SW5WelpYSWlmUS41Vi0yZzFBelRnSVJ2Rk9FZjl3UUsxVG4xUDRLNHh2LXNma29Da1dPWGpNCg==
type: Opaque  