apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-manager-cluster-issuer-production-secrets
  namespace: system
spec:
  encryptedData:
    values.yaml: AgBSm7TrqY0TDyh3SoO3rlTYWdxueIARN5q02/Ar1YAAzPZXucVGBBL963I4G3hbx/PAhDLWretrEaaqcGCxq5NwYCc84LR0TyB7IspQn3vCBOg7W9c8i1I43RbuO/NUnfty6LDG/WuP9vY6PBxRYWrUNu572Y2P2/u9290qUK74JnR/eZa6t5FOwVvgkHrzscH1ugQw8SJKpSGhKsCKNKDqKJYHa6SIwBoxRDpvuyEpFTQtgtp2WUduWQ/tKtjQaOAVEoh79okC50rp/3K3MuIMBaF4I1uMnDHk7M8qLp4lqz7QO+0Z+1UjgfedDBmXo4NziaLjzDl/XzdNS27+4EuU4R5y6gdSN4kwNxPAxMVKXNHJcj1nIUuCU8Ih2uoQeSFuJxL/7HgwUTG5vVmrMpKlFMulciOZOjEFNpOYC3VFR6IGc/6rnB2KcbmXmqCpLaEx1UvQ1FoVN0dxtfmlfTm/sslORheC9Hk/YLka5zgD9KOp6eTqIfOv7KfLWTZDG9lkOD2vpkvBU4oTVcKXqDut2+QhRdgkMfefOplSS5P4x3LdZpjlZVUFEiB6W/RvrwFKdikK/DgWc/m0VVGZ85T4mcu0siFX+qNRSc4d/S6f3ML/ZgQE81vzftYeltWsZP2Oef7iHl+Ewp//epgIgsWwTE4olxzFs+C3q/CvTK5JZv6b8jUbSBEFowYIKLXnW6w5zI0h5K58KNaSylq0GBqxt1JGu/6O6/BeeY2tRS8I8FAn3GsbVH7uOnMReW5Db3cHWSJNX+s=

