apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-manager-cluster-issuer-staging-values
  namespace: system
spec:
  encryptedData:
    values.yaml: AgAhQ5sGL3ihrPAw60FK3Lp6uGC6pi1HsZk0VUYc03BMRw1NF8GwtSxqV+3HlR9RNDA7w4md927rqMH7m/K9qLb30eW4Nd+Fl1PUiZOjhWElIusar8Fwy+3n5QQEzsXhLWqBJn+WfMdRzTC4AJEOzjcj0OpE1TOKPxOARCHIjUyOg16vI1C4XfnIqE69sogQ4c0NDQY4oTV88jBk/I6+zgSWJWoggg2UxkeFrUfIlW5xDwM00a+P/fgG0uSDVT7TxfFWSYVCz9J8CDZyxiuObpRXiASbetNG+IWmJmSXo6BHSfIFFHGgWJFihmrxHtlUKA6rTB7KtFQr+4Hisn2WTwwMO4xjELj/PirdIkaZFbY4QE4Mmy1UFcB8n63BbQ1JDxOnL/oRPQR/sOzIml+cyQPy8TXmla5LC8xOnhaIZV7U/DGZXuqVgvlmYLv3nfWO1vb/7AVz6rDnibG1I6AYN77YT+1u+npsw9bHb2ElAsu+PHL/IWNRs4Pts+fffPbQPoazJ3c/9Ri4gytqL2V+hMTWx5peQrP2uB8xN3TKf2/ii6DW8FssW6O8BPrxtP815SWQvUIUJP+yGxWPlfboXt9uQQH8bA0Z36gr39+YE+XsF/9gzBeasnP7yi32/Fd/yrfC5wpgLJ7ni3bF65h+5wkdt2MTMSZr4EYThc8T6K6X/nxyEy/PDo0rRUW5Yzc1Q4Ghyo4jCAplqFPPVRKhLD/WukGXFjx64mKGPXzZf2qw7wcFM4H7SbVnHGzxVOhx7N+bq8I=

