apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-manager-values
  namespace: system
spec:
  encryptedData:
    values.yaml: AgCtwd7yuQm5HtV+qpwtSM92QF/jvlid70vUHGPdX1WGcgvhxlU8M349GMiz4C4VV60VWU+nxzNcqYGhj42ecLmUEBzEaHZj1PqOOYWUm2znNhR+5jay0B2apc/yzXat4nV3IkJ6VlKfgxdptyo/+IkNIICsCHlBc+yIDIz5y/yjoILcaB4WeBPaLRw4uPmxoLWheioJ7LOhPSwObI3lMEVp0qcTiQLEQ2Dj0L23oaSI40dkunFNFGMHBbccCp5DcPuGB3mG+X/xImvD3N9/cD7Dw8FMKLKlmBWUDsR9PgbvrtNk+3zyRR1vsY69wYmjoXC8r0PjQ8i94hPh0t4QpKTTkFiO3V5TPNOcT2Uw/FRBF4OfhiKz2qDITcReGGVHQM70oZ3sbGyY4b9WmyH6SvKp4m6QkKrzRZlEiMNR/kBoR8tgVVUJo8dcmeo6JmqD2rCT24sDRHUE1peAfQ91u4uBhmkTkzI7mRklqM2RCzsNY5jTO9M/evGXYNDZyrZXytZ1xNFto3gzCRPZbMhyos+R2NvlwSX/kQLPU2W1udgRq24SLbzpY6fa8d18djMZ9H807dtVaLBLl4GMob5rjAS0bNJQWyQErmmaDfYrzMUU6EuXaEf7C9UEVMcs5JqxAVgxiSw8+ygY7Zz0zsu6X2x/QfBz9dmS1356ynyprLa8qVvHtc4dqEN/kneUKBumB9lCBOfCQZBXDmLqm31irF9xHWU2DEfGNXWFwkwseojt5pBuNEctaLqQWofyZ/SWzRnr3uHiMc2KtS5/hLESMzJyohgqo1fE98Xt52jH7jfEr1SpUAp8zT1j

