apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-manager-values
  namespace: system
spec:
  encryptedData:
    values.yaml: AgA6TWexoV67n47N0M/R++YfrXxv8dpefmez9vWekJ3w8HvPLk2b9tUGlHQ8MvX5RCAW5XWPk66le74GVOcd1uCuqX6whzrcLbU4PS7xFOcD0FatsE0KMiWRBOQpGWOiEzvEeFMP5O5IsluKzTYxINdX3S8r0L4KVrnVsBGmo4kuYQOPNxZpReF6IZmTOosQZ/DkMPwLhqOHyqJpdSPMW8RZas49HoZUY0UVAYq82ymfrPQX4lrbuatkr1HDRM3hrhy/keEBCcC86B2VVU6mHqJb/aO8Yb7uetAVIooZVBdGOEJ12ZQ80VQ3czDnDtUYKHiRRouCiNQ/d4WWWyZI7UUFwOX0L/6m3hqz8AVn/ekE1LKb7nqkth8un22JI44+bSqJL8zqm33JVfd1+JuwpxdK0f3xAz837+w5XX1jkrme1zVtIMi3xHcIA9EpA6hSaXFM7XCYNtGtibg0kGx010hHWXQqwUxo6AGZt8gESdKFO6z7l5yDmoue8/x9cKDnpGM+Fw31VmqbGqif3UEHjMeS0G8zgrKXm2aHxUcWwQps9LPzdQNesCLVanHjiAprE9N1BTCS4j+hPeAOc5c/a4Fi9DzCje7BVaIJy7EfF5HnEvWEVCoEAFl5qAbeIlY00gADVEF5abYwCTSU5hbNxw0eXCw8yBKGE+SFIJeQKpN/GTK0kdr5jN+b6TXylaoYy1bafm2UIl+/tLDa2DybF3q/n3e7QCO5tOahxqZek3DNSwwAMIcyAvIMQDtIpYf4Ul2B+xCTho9nnTzPoIPttQhneK23UtQ578dWJDrnJFdXoze5SJhIDXyS

