apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-manager-secrets
  namespace: system
spec:
  encryptedData:
    values.yaml: AgBDdIS2lU/Jo1lkd4LIsuf1MbCI3/oZLnCg9rBy/7WJSINJp1U4iwe3V06/WBl3kOAZPYjdx4STiX9F+BgOqF3fQvaotpCLgTNVbdOd/XGYJ7ppeFCMeLJ68cTxcabZcy5ojgNOsSSh3VwBsOUBTkHAmwfhy1wCDgzfo76tQePkzhk+ZG3dnyIBy9SEbrjUlunYYtzvZydxt0YrJNiE9o4sBwVJsWLWOU4Mn7g3QNW++0q3KCvyKDm0wxoo5/Iyf+68ExWNSRNAy0l+nxJflrVBaKRC3voX3JcLL8IQfkWqgB9PVZq2ehupKh1rlkZhKgo//qEAP8rd+Wv74uRXjYASwohLPsBuzkgiTd2Ue/MLapTaleHuE3qdudzUAG/6UhH9MIfeTUrZSQ3vmOCGM+yZP8St4huz3/20nXk1t4uNBm+BdmCarna6E+9nmXT2lYaxH0JlhyhvKmmnYzPiFJ8WXnj7JtvniHwNq51Di96MIqZY84wCE5wFCnADhgfw9Ln8/l78CpU/gpSzvyKp8A5UXOIECBjAD6hp1mMkYyDSVPTU35o1kxMlkvEyhqWSDLG+kQDjTwKTzDHQwmA1rmZcYTRdd75eQ43id0xh+aU5xAvwsld+CNnmRQpc8IV8nmSO2KKWl01fxAQwHCxBqTBuBdljdBITZqNtc8pF6y4jWibPq6vTzNI31a5jhVU0/AfSF3T+OqWHYjOmJxuu1JvaVhVgUgw2IFW2aRt4z5GN/Ou5Ch66+XMMtvOserZeI5ssqNEjO7TzfAfDiftxPmaU8z3DkPewhOm93Fj0b1/JRmsMciXOrb+8

