apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-manager-cluster-issuer-staging-secrets
  namespace: system
spec:
  encryptedData:
    values.yaml: AgCkF7UW1QpNJwHrqRnIxz5+ddPcfZukKNPjGeverK5E+dsZwYpCh/BhJzxKViWc+OpoymRVIsiI4g4abj0imFxad8qtyTsGhJmcmPkKU33v/6tBHyRftZgvuCfPk7b+HqA5mPepigUci5wdQsQrqCYazxk5cury1iqTKF4iYJ4uF2EySacKVYJ55fKCVxgixduHoyeikMRW4Fg7qfrmsgEKBBrlVrdunS8HwZA/Qny4Zozc17h9TWEscKW4hQOxV9SYs2ULFS6ZRHNtz7aKoLGiqwvFcjFhPKze5EYlS6xgGqvP1YysCvJRAy2NzhSAKWuffaTg7rIO+pcSFQZ1rcMmILgqCA7xqCtuAbkL1yMq1uOWfvNYqZxCNU73/uR4FdzdMS0dPvHRYcPPn6co0Gw7XHb6gaSNiREkyY02mKP7hMeEkaQqufLWj3l6mcHbYMGmR2jIuXF6dJQg33fLyC17bwif5vulqV/IOHjEGpVjYTdBZrp7QISll4tdK/F9Ydv54ddIrFFTS6emQcrU63IvOlKEIF2y07E9jMrARLnLRebSLseWe+i2NKT9lTTg+Ykc6/w/DZ78SemvxVNzCVyliLwYqy4tvv+UFadto+0E91U2WFtIZxRcgWmy6XsmkSa917ecb76//TnAS5cZL2SkQ39wFqZYdiiCaaM9xaJWIuh/UAG2Y7J/2hb8PcVIxZbbQwGrGa/Kt6IEiri8gEKxS2wZf5Nl0TUKvx0/2aVG8+TS5b0kgtlfyVUa/f4THPyNuas=

