apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-manager-cluster-issuer-staging-secrets
  namespace: system
spec:
  encryptedData:
    values.yaml: AgCdi1LRMI/s9CokZhvWH4F0h1Xqb+4Rza9FqMnYJJDFq31q9rN8geX9rQyd0eo3VgNKEQhkqa8EB8JjNfMg0NK2LEyoMyUQs/FDsm8Supk5cWjwiyjlSTpJoIMatpIDNKYjjSbRfo/h/FUBBTMduX7t2Zi8+ZrJEqO91IpAgsvCphQ6I+SrWxIz5P0RqwjWqN59cx+StXnwzCtR2+oB4+3Idd2kUGBqR1Mch/0XQ9kMp64q8BRdNKYJlD4HwUTpQ6AItInO2GcP00MraKQKCliw6ZMEILgBEVyq1pHYRLcByn5Y8qf7Oci46b3GqLmAu4cYMX0pH79JNlwyDCi2aBb3CGKH5kiSOugQrXY51xGfAHCfGc42U4laThAAHvqpsaS87bMMKi+Yb3BY5jWddXRfa0qexJCR3pDR6UROFUedaibiEVCiGJfymy3fpsab7tRQLAFlAKX2YFHqXjEiz8CsaXHIEbJVNfEaatnh57iMQGre5UDjnv6s1efFO5FiOdonSQ9Zqbx4CYuCwrJiON98lKGpFPx4gErnJIwtQXdSTsuGrlUoszy9QLZ3IPNpjXo2gBL4CfhzWDN9Iwvo+plFt/Fpe76uuAh8+EFbKAwNrIdeNzvZMco6Z6cYjpiA18QvMha4BP0dBR/o6kn2YhiEl2EB3T3VttaRzu3Gjem4mW/IRHuL+w87toEJPkE27e7s7w1eJ28N5OdTeIy5UM9HD1JCayLM+dDKdccg/nrDmEbUXB5egVuOHd/AYt7ZbKwM0ZA=

