apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: drone
  namespace: system
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.server: semver:~1.0.0
    flux.weave.works/tag.agent: semver:~1.0.0
spec:
  releaseName: drone
  chart:
    # git: git@github.com:Morriz/mostack
    # path: charts/api
    # ref: master
    repository: https://kubernetes-charts.storage.googleapis.com
    name: drone
    version: 2.0.0-rc.8
  valueFileSecrets:
    - name: drone-values
  values: {}