apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: drone
  namespace: system
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~2.0.0
spec:
  releaseName: drone
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: drone
    version: 2.0.0-rc.8
  valueFileSecrets:
  - name: drone-secrets
  values: {}