apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: drone-server-secrets
  namespace: system
spec:
  encryptedData:
    clientSecret: AgDKOIMwuVRvUbX6LfXdrFjYpFoyNctsU11Xz43MaRxE+KZTByvtP4qALUO/cgLVguhxI82Mwss4pXamYnwldJL9aDbcxttxpekrcqF3mQbxrVkP7sfkPvqS1C+3jdOv+79593jqgoNc7Q7jjY+M/xj05UcoGKFP8m2XuRXltT47VvUwLx9XY2UMb6G8Z+QkbsEceE+OinjX7aBWQ9YmAJOA9xawCm+usJrrXopBIdgI1r9MLKuFwBuTfCQEmAPMazMbyLs3u68wP1rOnYdSvnDGSgcsn/rqVB5yz0y2Win3MvIErRAfhDqHZHrD9IcXN9XbsSNvSR1w310B8ZJHTljXsRcDKTlKyxLNVdd3/Y1b0CfOmeJH85pPzD1JcBcRwCghZuxUCutCgCgQiw7+4zdUeqCMXoRlNXj7A6EFAdI6S/OznY/1cwRBv6bl9GPTaNh8s3pvNG5VxsoY79FvTxYIDUiLRnmFJ6FtJ3GYOhW3bbtj4XGyaQrf+dHjtiyNtCJERw/TNOE6MyMc6sRxXaMSPSOrgGYGKFjLYnOYZxqV5nsvvqdsZkuo9gkmZiXaVyEtOZoMQm+3vpfbJl5+9eKCojoTzqhk3wvSehjLsdsrqatNR5DAdNjeUxUt/wrCP29oc6h2fGFJEDg5IPjjdrKeWqx7ACxotDdUa18zmefXQGA9r7BXrSL44JtsutrEDhYW/BtaM2YEfZiPbpnUqGq3T5i95nalD3dbWljz1QpWznw05cUmyGgk

