apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: drone-server-secrets
  namespace: system
spec:
  encryptedData:
    clientSecret: AgDV8gA3ixoEfGuyU0ngUh/uU1H7Rys3XBqOHAJRVvqGg0rfRUGB3PNKZl0K/9nzXgZz8UH1i0i269Q7ZAGeqx+3uONHoyWHQso6c0z2ThT8N0OfNrgRB5NJolc1DEIjNSkaNCflkWF7fhqBYQaar+7GX/4Vpudc6muf7Q9foG0yfZsFoutuOkB790KfatbwT4I/Kx01N+rAo019gHTRHn3Cn6JIVQHulo3CvG7xrKPDnvZ369sNWRvQo+9qM0uvDKMT+qg9oNdsmLaqvPXKgqyz3byV9GJCPEju+SjNqWAoCGSYuNuVwKYc4AlMlCEm7nhrVYsR5SgV/CitJH2/suNGy+dfHGEnAN+Afl4unYgk0rRNWCgGGfG/z2pMuzLkB8tUQn2jrlEklVXaWZNALU9kl9T6akJc8TRha6I+e/Jf9oxzNV4YO4j4leucitAzJqwwivDpyuqJ6jEyZ9dX9kYs6LUDyr9B1KyyOVcqryOKzjPg60bcT9d/4K7WUCTqCkNe8BBhtAFfXtQVl44iXblI/zmNTwAS4FH1rh7vcn6/taV9hsRPv6JecSUEX/XUzgxCV+zRICRbnhdgArkNOeNCCtWxG6Qu+CBkZKgOwrgKT8VXGbWw89BRpMzHF2ItvynuutqnDQED7olfxLMA+gYKzqWtUz2Ts2kEYK2gmvhRPRGcRl6aAaEHpxmASlJGAtNvLEVEzaxlimVDmqt6U0GW/TifY9bICipoDOWhZzkt2iGnxTpjE8RpFA==

