apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: drone
  namespace: system
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0.1
spec:
  releaseName: drone
  chart:
    git: git@github.com:Morriz/mostack
    path: charts/drone
    ref: master
  valueFileSecrets:
  - name: drone
  values: {}