apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: drone
  namespace: system
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0.1
spec:
  namespace: system
  chartGitPath: drone
  releaseName: drone
  values:
    ingress:
      hostname: drone.
      tls: 
    server:
      env:
        DRONE_DEBUG: false
        DRONE_OPEN: true
        DRONE_DATABASE_DRIVER: sqlite3
        DRONE_DATABASE_DATASOURCE: /var/lib/drone/drone.sqlite
        DRONE_GITHUB_SKIP_VERIFY: true
        DRONE_GITHUB: true
        DRONE_ADMIN: 
        DRONE_GITHUB_CLIENT: 
        DRONE_GITHUB_SECRET: 
        DRONE_PROMETHEUS_AUTH_TOKEN: 
    agent:
      env:
        DRONE_DEBUG: false
    shared_secret: 
    persistentVolume:
      enabled: true
      existingClaim: fast-pvc
    rbac:
      create: false # we will give `drone-deploy' roles to the teams
    prometheus: prometheus
