---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: drone
  namespace: system
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~1.0
spec:
  releaseName: drone
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: drone
    version: 2.0.0-rc.10
  valueFileSecrets:
  - name: drone-values
  values:
    image:
      repository: drone/drone
      tag: 1.0.0
