apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: system
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:v0.3.*
spec:
  releaseName: metrics-server
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: metrics-server
    version: 2.6.0
  valueFileSecrets:
    - metrics-server-values


