apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: weave-scope
  namespace: system
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0.9.3
spec:
  releaseName: weave-scope
  chart:
    git: git@github.com:Morriz/mostack
    path: charts/weave-scope
    ref: master
  values: {}
