apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: weave-scope
  namespace: system
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~1.10.1
spec:
  releaseName: weave-scope
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: weave-scope
    version: 0.11.0
  values: {}
