{{- if .Values.selfServiceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  labels:
    app: {{ .Chart.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    prometheus: {{ .Values.prometheus }}
  name: {{ template "nginx-ingress.fullname" . }}
spec:
  jobLabel: {{ template "nginx-ingress.name" . }}
  selector:
    matchLabels:
      app: {{ .Chart.Name | quote }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version }}
      component: "{{ .Values.controller.name }}"
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  endpoints:
  - port: metrics
    interval: 10s
{{- end }}
