apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: cert-manager
  namespace: system
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0.1
spec:
  namespace: system
  chartGitPath: cert-manager
  releaseName: cert-manager
  values:
    slackUrl: {{SLACK_API_URL}}
    kibanaPassword: {{KIBANA_PASSWORD}}
    hostname: logging.{{CLUSTER_HOST}}
    tls: {{TLS_ENABLE}}
    containersLocation: {{CONTAINERS_LOCATION}}