apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: elk-values
  namespace: logging
spec:
  encryptedData:
    values.yaml: AgA3MDi1Pmc/qJvIUEnfCmW6JwC9gsQlTbsQKme4qjKiLr6sr8URU/val7spMDAefYvkzg5C1v3g3uHLRKRsvH66nyd3LxhSUREyBVj7JT2FrzH1wZB0gsR4TIflSk1lbA1alndIoQiK1sAT6TNLIPJwX7+wo9D0gSqApU4v+Uxmy8JX+pnUlZRq14Vrub9nqR+Aj9jhqufmgst2Pluoxe0PLkoLoXWG8L2L5ccW4M+9/3l8mSXGD2U+e550poCkAFKQpeJ7i9IJtzw29TmvDQs/grT41MA1VdGFWHCMEqJenr63x/5loFWUapCpHafvy1c6Zml1Ki9gHHmHbJmq4yR2zr6zguliRolFSaXbVfT6M34n6OaB99avL0dqPDCO5bW5dizA8qpQbj7NyuWg8Kok0SK1VuIT3GgZjKZ0/R+AAOzlr3bV+Myfd15wyBqEHmyctp6Iac41FGnTfIjG5bz5GH9L5aKem/cIzrPmp4eLJmQfTrpDYV5wUMM6XyTH+dx/Qrp/LchFQqyGzHlN94UVyhYVLfaN4bR+Au4uBGIVHIAmmkhaRLcp3o3eBxOWiG9UMI6X0hS+JrFfyTtBgGEpZ71V8sQqu+pItqWfqqQ/U9QO0O6k/seN/iWRZ4zjgp4XxDLhh4VbmoeD6vk0j/39mKuvhoiXPkyT7jSPjZ6+DrrKoJNbsLxWq2m7lRL/uhG5kAENXUpx+ifKbnk0Ep16GDzHsp57F6cX6t1Yk4ICiUxO9amVwJWHHFSmeLhyoSpAP9L3tAIopAavHLnoUp6dde2Ul+D+C2XSWxbxVKHPCgn1u1JdEGRIgjVJcCpBT2Vm1oxWuYflv4mjCxfvWEpEO3XY3af/hbRF24voFADRWilEqYAKXhHVceJD3+9XhV+sTSI7Qqz56ID1YtmX9rFJb5E4zcubhQ==

