apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: elk
  namespace: logging
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0.1
spec:
  releaseName: elk
  chart:
    git: git@github.com:Morriz/mostack
    path: charts/elk
    ref: master
  chartFitPTH: elk
  valueFileSecrets:
  - name: elk-secrets
  values: {}