apiVersion: v1
kind: PersistentVolume
metadata:
  name: slow-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  storageClassName: slow
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/Morriz/Documents/Workspace/playground/k8s-dev-cluster/minidata/slow
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fast-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: fast
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/Morriz/Documents/Workspace/playground/k8s-dev-cluster/minidata/fast
