apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-values
  namespace: prod
spec:
  encryptedData:
    values.yaml: AgCYflOLJLFRcMfdK5fo/aW5lzZ7QD+moIP6uAD3IV6M3h5J4i/zT6dQLUq8WM0N3iERTTx5Vu6kNSqYw2K+iqAv9ttQTFiQwcs3KR7HWHTvgBL8dyfx1FK0Y4jIU5RzehJzkZYtE3cg54NS6qQeT4BYgsMduni7UM1zXEharwUObi7AlPusekQ3fwIlRXKVPlFNasTvnknFuNqoAIhKSZWLHUTN4CwB/jNXACP+P95D8WO9mb9isyqzXaZkDLFSB4fxMb1wrWy+vAcwPdZGK+d4gptB3cRU7/r+L0VSJ1i6bfp8xrp7/k2HHSit+cW6KZaHiMKEyxFPci5MnCWYrLSrgdGNSwyKkEDLOc23s+gVnDy59ZcXvWQvbiNo3uDy1NFTXHvt6NtQZosBPNEn5rR6OS8kXxuUN8rfhul+inSUOSZ/YfKMWScolJlW1dxAOOetbxNK0l4OP9bQdYqkeoorzQaMVz3s3Oqogkch3RNsChn+zh8sKRRkZeQ6YBqH/U9LwoZVYIdtFH7DKYxFChSr3pPt0JC/EFeSdSGDNsFDP/BLXsCkW2youj0wAQWTKIX2brlt2qMjJmESIN74Jllq9YtNR0ftc3oJY1F+sFZf9IaozK0iC52L9dieWBGVdbq8G3l9zzx8vhtahn0tD2PISLCfRyqsKyuxvY2t7aQXuhz56SQmHLgUEWrJePQ+5H+ps4ag8QfY76/3MJe9sVXYYzkKepyEamQoHx/P5yuFHS7XMqYyMXMx3V5j+bvRviPChMKBXG1Gv6Uy7PtIQ/4jidxt6Gnt3bkEzi9/z0D4xHVRTdKkYaKucBeiFl34/H/FXKBUlRNNtGPeAwsBhjk+dOFwhD7iwsnDpLg1U0lxCJXzmUMKShGUJKxXaFfg9CpRNPPm5o2F1fBqFFWZdcyMvW+xUi4dgzHD2FZbiBoOL4lQPLn1mWW722WOPaQCSvGmC1j/8Chn/vtqJRg33Up8RMpsFfcpf1CMidq/NfK7j+JkCPvQ5cb6xPKCfJ36tQT96iG3Xkew92+QZUy3Vz9ZShwa

