apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-secrets
  namespace: prod
spec:
  encryptedData:
    values.yaml: AgBn+KP59k7T6ZxrzCfnhAr0dLuEtJKbrZ808N0bjKYPNiHteqebgFCIhKuv/oqRhc4FWMoLku41lp0SpXbnVGbVc4nneNyoEif6yuA0DQhV8t0hvhfqYJec9oGxjrFOvf9UQrDR+PgU1gK4oC3sEN2+/s3GLFKyd6NQke6SY8v+bodz9QS0b/gseTEQvro28KNrOwybDnNYtBF/zyhgVZ9r8OUmTkfZAnXWh4D5k/2PfkplbsI/hcGP4YolcWMz85JnWZKD2jY1S9uLgsj/ODJtO96Z4Bqs/XCaMR+/ZRDuz6WWcF1pvurX6HxCNFsiON0cftjHydOcSvWBqQZ14JYX1edxDrvyPahSKSlTvttkgchAXEt2u0rj5V91cxrXvvCsK4kYbxmkyKCdr+kslCjQT9x7AsqzstGx4v6cIGZytUd4uJemY4qv02AFTP1Gc5s3rRQMgExqO6lXl2MR1/DACkUCStmXCaaF0BJuwfwe7Z9ftenaeH/ygFnLs/nCMv++XAS0YeAdD67HBjZr7Z9XkLPu5ZiJEy9zMrAty9qsEeDOKIVajy+2N6qpOCjfjSI3lCQ81qUq57w1abupk0G5PhrHTsDEyHPFuLJa2Z6L5MuEib3q6zOgBXHNaoIRa05Lq6BM75poNqEVSdrTHFaU2uzD/buRkfGOVVxZqjBNxuiwYk6bnFm2thTbA8vLs0uJ54aZYoKCvzLmV0ID/kpFOzqL0WYDVCDcHzANlMvuLnOvMdLjHJ12EqgBwmq7A4gz3bI1VuA1ji0HqyO8d4Igc7/h4SQD/hB/2QyhloR/rR/y1d8l+51b+go+sPjfMyq4V6QefMGad1fhE1LuCoWfpMfKrfMaDHYiR5jM2BNEVqtge2PBbpGjpTL2OVE2wCfT/qb/IXM3vj19gHInhCVFsvLx+/6k8QlhZHy4i2yyM/ASR/V8hwukhQj+NL6iMwxnW0W74kIgny7zgJ/Xbau53xFqK1s3rTtAgIfUGX70VmtOcdXz7RgSrnVWrhQV+XzKk6GWc5duitFG9Lg=

