apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-values
  namespace: prod
spec:
  encryptedData:
    values.yaml: AgCvwUy639MUvylTN1T2l1W/CCGxNyao/YDHs+ycx24jz0a5STDTFRLUABpjLapwKgY/h2aEbokJxQNHz68e6jNLmR/Yy9Fj11o/JWeEwEdq1IVtCpiQJkEYjhXs64FXoqYQA85rscCnABnzd0VaNDY/1M+BGOQm9FNA6uK4YJBz+XAEF0lCHtKiCqV0CXChBOymary3SELxcv2aZp/4F6okAGEqxJhB4ZzUAS8Kk1N+pTke+1D+A5XfTMvTihmSqwyMXI+d7IkjhX22+doEudSS00M8BRGO7ZPyTZBV6IOCuu9zu+THAc/cY6sorKB9imD3uYWBdSYT3Wn1CJPH7RIFFl68PRdkaPQ2Sc3Dwz+gaIBD06njcZ1FzPyUVsgrKiY8BQz+SVTD/pAKzJMFTsBTUcLurIUTkUksSFr1G7XIkiJz8aQ1/8ba0cffH/5NrMCSsmE3ks1JjOYRRukEFgca+Ysi2HyJtghtqJF1+OW7qNndfBoQZHyedq+mX++Go7eQD3P2fuD5ttgT5wRlpxnBETBC5iX7oNzhW987qG7buv1zBZ270c8GAbupQJOOwPpXcXCHygSRO9iKVd3lAWZrV8f8czFCFnGn/1lShvTVfKYc2Kh7hBVnqDUqZBiJkADCGeRsXmbcoPdLtBYx2tAl3uQE2mRXGuqz6eDvxVZ193ZfGDy8J8IybScuM3pU735LMHZP+Xu4qDZae+4Y0wX+wku8lTUQtK60nBo86DRgpkErpvuHmsuQ6duetcohPH3SBTYLZeUF1VjGVvVr1BG4R7P1O/LtMb0t9rEYwtbEW+BcmSQHrruYCtU4vRPhEb2zIgPl88jBmnB2kw49cyriBA/UwgHc2qS1dKobA0Hh52y5kpASbrDXQyDMmWPQFv5+tE6S8ni+7HniIGMYU0945enbUYBmvozgUFHo1O+A2ATSg0iRpQDYQSDyqqblsQ9n8F1fpQJe+tDNkX3oDIfR4Oj6wLEXW3pI5eojMK/M1z5Jc02082uh16uV5ISwofDrFClAlXvuF5vEobdQd/VKag==

