apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-secrets
  namespace: prod
spec:
  encryptedData:
    values.yaml: AgCz23t+5bpfjShwAMs1x4HzkqkpxqI6xecriFQA7lc5TepB2JF5ZMHnPgv1KiXCD1jAmyAOTWsyC0y9Wmdq3H6BS76n1/22870fUgedJ5Ax5csxiumhxtFLh5a/8+89vZqqOdXDVWdFmsOVb73inqTXkysuFE/iypZTdeg3D/fT09f8sNYiKQFA24Gm7GJk5CB63lhxaajCOegfwlKOfnco0BP30Axjw8//DJNHhfDmaIu82/miGgk4hZdmejmq+DIE4CKi13q50gOXgSkFA//mbwLrT3OBIJLdBxp6AB+L/BQY+mLnooXSGqSPvcjTQ1xcH2iey/dRRxn5Jq3aLYt/kVGqhPlw5u9ExPW/p8uHqMskyYwrh1xxmW28PlvNAJNvOqb4ta2bvrjvPn0FuqS3aFHuu9p45mR3yx2blljgyDSnUd59WRNpE0w7sNN1gx9uM6PU2AmwyYzSqrmrTePXSA8O6dLgrLoYdEp6hewjfbh7m90v0l9VqacFYvuXZc6dtg9xxx5bKevI28JivMMZyjp58CiuJjhQtrMhrwqDKAXox9g2Xq9WYmVlrMl0aEVW1Vp4wEH5XijJbv3Um5gfBkbdsCPx+ey1vpIj984pF9+vaMplQ3pIMoz/eE83IiijctkIPPNqaqG3iBueSC26un4sTJBXz3P8M4sqyQszE2HZVLWr5sgXy9QLAP35OyTjNWYiqZhVqZw7DwSeFIEUtiZHsOkPKE4LvOdcz6J2TicZrqSmC0Q8tHz+jnnOzKL0tjfsf4BYoZ6QsixBoTC68BODDeqYCJK6Bq+b4Mt8kO3QBO8oWhcpVkfOucRzjz+A58OBDX4YMhy3NRGGqh5IDfohoF+DkuIYaLa0sb3uKg06TeCHu7kL8lSZz5GPENY8NF138zzXpCirsvXcdoG1RWj4LKKVQW7zzMtcLIR4lcUoqOHwqkSfPp73CpsisoaS456Mf1xEAPul3kTwBtiydT0PZQF6oJ3gPYon7WJzw/9kh5+XE+aVAkC99yCDjuEA+YXepjw/WQioVzkye2l35BJC

