apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-secrets
  namespace: prod
spec:
  encryptedData:
    values.yaml: AgCnBci/P44GIWDjDUIQE2lpnjZKCMh8HTVWrQTYlA/+2PfaS7XIHKfRyUyK2z3sdV17wCTSGG1TTgu/n+wTpZ/nO4xZ0ZPGst/EeDBGzYiKxEgzyvGg2U0LCFSdb709CbOCeGbC/ohl8N7QUWZlFoX4QTdo2Jr5v5ac+fFsdpHHeTULd/sq6t2vhAYFGlett2MIyGTa6VXN6wovCcPiTGL78YvcFf78r/fME6xi6uNQxsjNBtSXp0TJ05mRXyP/TFZBybmWCYyKqJsCaBUu1lqCudbSAZwjxHCr61kDBAbmMphMUqAWOX5I49cFRoohDag8vAYehh+MTAWD+kfzTNM8ogUelvzD92ywp5xeRiSq+pfSIz5qgNbmDuqSAPxv+hc9Ky9R8QhazTItzXsoCXnZK6qpVVzXOQ9UTZVFN+LKJAJV2VcjFjqD62yLsZTzNHH8HyNQd6X9Eee1fZEBKJKAYuPeRLDXtO4yZMf1GfBNqeYCPWDEV93fex0d9s02lGlexeJTRdhNxTWenJmxVj0or+SHtAYDwmBJtXJYLtkbsfhrXYyqva3OchRQ/7dt1ZyvmcGhzSCvQ3Qexu03mv0YQbXrOQTMIdSC7saeeAsVNAYvEa2lFMQBrU2Zb/PLlx26mTXLkT2yC12onQzb1StVVeuk/p0bbG+vqlWnJivVvdPT1ALXnD5ZG6G7jVKGdyykfM1EM0XHaKqHOzp06FnKGmSzYWU8n3Na50VFJGDl97tB7tp1zOkVkiS7a9VS36f0GGHpb7RjiBNN/zs8Nw9/ifSKXaM92ElFTMTKxoGVc+hoX/PMFIIJBznF7d4CW5SmzGoZmnKXYB8gLmcOwCfT44aBS/BafiWE+q4nCGEBuD3boUbTDY+BlxHzNZg6ZYpqW/rNTO1AnFcY6hjz9bnZrmbRgLGhbgdHuaJoRmGedATMyHzQBUya/J70TRez2HnbueRM0DG4Ke2YTg8rKjbTvG4Fln1+6jeXE8BHJVgBWn3K4rzj7A==

