apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-secrets
  namespace: prod
spec:
  encryptedData:
    values.yaml: AgATQlD4oTwWIhkJowS2kASsAKBm8q019+NjhJcrNEqPDkah8C/BeJcbfz6t+egcn1+IWBuLyJChLvpJHgjmw/Sc1SeF5xy89qFkkxBuQzN+UAWDG4X97YKtWZeSbUvxLlaBY8ijXNl7mIMIfQZUm/eVWhyg1+2COwn4+jlHKB+cWbP5peUs0el6I01TKO2ssCCdAz1YCkOs7yfjCqr/VV37huOK/XUwqsaWjhgCjVU8zNmkf4oo6O/GXmWuDiiGKpHdMRBJ6Fuzfk6ZZG0aAtK46yTibBsDPiNtZq9ecX3N/EvCrkeXxD7Z62Gkw3TbGm9WYEXryyuIAkAz+s8bzdcDKcydnLxjBn0qhQF7UTXhnkzJYDgMzmyda59U22s0gzmTA00MyiUdjhup8TV0SQXLtyHHygJLFO83TWx7ls/dAzM2GQELuLYYmqZnuZB/xaZuvzuVbdy5/+6drGGwobqMVRK4OgZbUz3RvKVXFuFXqAnXIAd7oTdxqfRv51uX5Xhd1YukmN5+ZFyB5JiZH1jz6+E6xmIYIuvDhbkWfCtqeBz2lBsXlDe4PRtqDOWuyG4SwqKawXlwQ/UzsEIRVxzpWEmvGSHB1sQK+uNTZ1/SdRV3OCP7MOqLVIzQy1kOJREbwYIEqxJMjxqpWX89eBIzMtY6Bo+AaQxbsAVN92IIPvj+GzrW+tmLBfx4fnf4Z/QxN1EeAqAFC8HWHBdOqgxfVrVVhcVSicDWg2uacFlrWAsAKLq4mOyQtKJny++WCmp+xywb/3mnZHM2kMBA4TuxTkaQQuN6sk3sC13JKjKJDVXm+TFmosARWaFLCAFABWMpy/O2wETHYj0mlm494zb0DruMkT/Ft7l2HvNoPaYoUq0OORmKEAz1h0S5Ltl/uZmeFasGKPLgEciIeoqgpDvW3klpu9JNCNbYnQIOB0Sf0FQZX/wHCcifckRZyXUct3Y6JWVbJM+rVRtQtq9gDGlxI00PpDka6GO+x9kimjY4uRJbAhIp85yy4RGoIDQRsC20NnvmQ9EzGYDDj8PzR2DlPxA6

