apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-secrets
  namespace: prod
spec:
  encryptedData:
    values.yaml: AgA188RNY7k//pa5ot6YEJYCoJGbm5c5sqoC8NwCIZ4/CCEtnDMnng7V3xltmuVWg5F4QlUgxgDwIKExchDYolbT8BSN7ozPVx/U23JdwmrQmYwuiwiUvHr3lkUctv/mD0+GLh9RHp7Zapwsv8ORa2riAw6GbJTVTsrUdT9zc0GVzJ+fCCTD98fWN7cJnZf/YeDZ38APO7PPoyXYce8dTvh67xWhXivNsbGem+vSJ0PJOdkEGTvNGJ2SW2VNM9xkBMhpQbhT6pqmKUhmOU2/jfukmpwIZX809Mms/uGiMBYpfLTlHL/2JcfW4gNIqF/o0QcgbmZjoK84VsTGUwEJtvJBl3vKsMqVcRQ0971snz3f8g5hq8H88Ws5TPnSlHFQKRsGBJrttXlHTRGYTnU8j5tBwU0MTQSzSKPgdjdEEIxsYO7Z85OQwgsm+J989POSZ785EIRNZqL3U10++1BhMX/tAKc2WDZQooKzip9++8OTUFktT27s2Da6On96C3mI7/BruCsFBkh2xmkZqGSwnZBE02T45XwlhS9+hjBblmzs+aw/BBJvPFJxpGFSF95CAhRpGID9wYZwdcfhd2jHi82NbM3C5t1eWmLwJmU9Xei2NHcM+XKqhWy/MbM5tUpJWEhOB+4P8iuRf53tWQromfXVr7enEqLpd45yFS5BnvaOrmEyGt2p2yeD1J5CTpkvyTHY2NtwGsID0gSIntXpTQr1btgJKe2KCgIRWQy055hUmd0F78wW4YzBvNQzFXOIUug8A5N332hXgc6wyuskUPFgcLGTxi1IkYNt3AIaPSgGYfOhYo0AbrbBJ02iJjotMGCAKTNT7779Io219UcmoSqxHwCeSpQ/1zz4Pa/DPp96Dp9zIlqRTts2hX/ITuPDvgzLf7+Mjat07FXoRH6ltFnNS045zlqmifv9hfnUmwyJfqkz8SKsdFol8NoLDF9Qs9b7G9mz/TQ3mdqmDpXFMIQ35epLGPopBoyriA2FNW/n1J8FLJvQVZt4GVVeVuO3Sd4HGWxKOZuQziXJf1go7p9Ni5La

