apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: team-backend-api-prod
  namespace: prod
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0.2
spec:
  releaseName: team-backend-api-prod
  chart:
    git: git@github.com:Morriz/mostack
    path: charts/api
    ref: master
  valueFileSecrets:
  - name: api-prod-values
  values: {}