apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: team-backend-api-prod
  namespace: prod
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:prod-*
spec:
  namespace: prod
  chartGitPath: api
  releaseName: team-backend-api-prod
  valueFileSecrets:
  - name: api-secrets
  values:
    image:
      tag: prod-e50be0170a6b8caa35a1229f9fcaf232b60220b3