apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: kube-prometheus
  namespace: monitoring
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0.1
spec:
  namespace: monitoring
  chartGitPath: kube-prometheus
  releaseName: kube-prometheus
  values:
    deployCoreDNS: {{HAS_COREDNS}}
    deployKubeDNS: {{HAS_KUBE_DNS}}
    deployKubeEtcd: false
    global:
      rbacEnable: {{RBAC_ENABLE}}
    prometheus:
      # prometheusLabelValue: prometheus
      resources:
        requests:
          memory: 400Mi
      # externalUrl: https://prometheus.{{CLUSTER_HOST}}
      externalUrl: http://127.0.0.1:9090
      secrets:
        - drone-auth
    alertmanager:
      # prometheusLabelValue: prometheus
      config:
        global:
          slack_api_url: {{SLACK_API_URL}}
        route:
          receiver: default-receiver
          repeat_interval: 3h
          routes:
            - match:
                alertname: DeadMansSwitch
              repeat_interval: 5m
              receiver: deadmansswitch
        receivers:
          - name: deadmansswitch
          - name: default-receiver
            slack_configs:
              - channel: "#devops"
                send_resolved: true
      # to have clickable links in the gui:          
      # externalUrl: https://alertmanager.{{CLUSTER_HOST}}
      externalUrl: http://127.0.0.1:9093
    grafana:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          kubernetes.io/tls-acme: "{{TLS_ENABLE}}"
          ingress.kubernetes.io/rewrite-target: /
          ingress.kubernetes.io/ssl-redirect: "{{TLS_ENABLE}}"
        hosts:
          - grafana.{{CLUSTER_HOST}}
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.{{CLUSTER_HOST}}
      adminPassword: jaja

    # fix for wrong selector:
    exporter-kube-controller-manager:
      serviceSelectorLabelKey: component
      k8sCoreComponentsNamespace: {{K8SCORECOMPONENTS_NAMESPACE}}
    exporter-kube-scheduler:
      serviceSelectorLabelKey: component
      k8sCoreComponentsNamespace: {{K8SCORECOMPONENTS_NAMESPACE}}
    exporter-kube-etcd:
      serviceSelectorLabelKey: component
      serviceSelectorLabelValue: etcd
