apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0.1
spec:
  releaseName: metrics-server
  chart:
    git: git@github.com:Morriz/mostack
    path: charts/metrics-server
    ref: master
  values:
    args:
      - --source=kubernetes.summary_api:''
      - --metric-resolution=10s