apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-values
  namespace: stg
spec:
  encryptedData:
    api-values.yaml: AgCpmdH3UncQ/pPzmmUyy1q7hf7SnSzlGQVy1OqRn5GblCjlKSXZr15n2TuID+GfKCTY92o2J03fJr7MzGfyB6dhs8Xjb5uNxpPVgsJsZwcb0Qkufa7mjBPewnwT7f/HQvJa7YPdTc4VnENMUDyBiAR8m4rwnhXCs3B8O914erXHlpTeluUCxEl2+63/h2IQPeoEg9Vuc7SgCnksFeYKXDTbeeD9TxbIrnwTnJ+ZGFuFU+JPeQ2JKYesO9YU9Az8Y+WVWlN8++24koB6sO/Gd6kPeAuIq5hqMeV1nPBIzqQ17lHcLi9K4edxCwFrAXKwM+HDq3xP0JLr1vwiTZ6W2ym5UIthwz2F6lLWDtnO3OoegmubDfDWk+6q8umFQI2ftm6Rh04oX1FlGJ26f79uF2mqxrgkCyRtaLgcqgwIgRe4N8eKB2aqkCT/9jK0e9FUZQzk7ASBPD3x5SbfrJPiPZcoIcb19O2F1S9Pa3W29+/AxGKSJxUrDyms7rI3JN0VilZw57tmleVrz0WW04YzMQblL1684uNnzOpV5NAMvoof8um9urMYWJCDqUswvg10O95lUHdWREVdoe9xsBBUwPy323vVRdwNZkU1BY7iB4ufo2HwM0qE2pkGnriXiyFKA5Thes3MbTjIrvtCeLX6RFzMWGj+u5jY4bALgJcGPszhXYGUWwvduBDoDIbLZOIaiTUwE+y0r0j4kq7W0c88rgEvqBUsDoBvFTD0AgLrwSCVlUq+odNuVQtbeM+L+QQWmp+/voHqANLO0CjVVrooioIGVLrg/pOIIItpK/nFSNK0aWjeAQ7bQqASeLFdZWN3nraxwoVbGhYKSRl7BC8VsB6cnpYgZ6Vfcdr3oqn/YLB6xBRlheYVMAewvlRPiWgUkMAAmjorYPbFELF8cHQnsYI4TvnCGP+8IvT5DgbeYpbf9PxG86t8LSbGYOZfDfhHgrvIa74aIfsDG6P72eeSoN2MnfxcL/n5p8ZxFmeAHkd81mPWW0wtuaYpc+8Ea5PMzNkkquZCO2E/dNo2lYzb

