apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-secrets
  namespace: stg
spec:
  encryptedData:
    values.yaml: AgB/FFo+utangHY0p3ecvHNgFBhWCyyE/kwkBOZlQht/7qvML6TF5RCvp01N/TW1f7kGMysSvLRe6OuOHPNh/gYlz1fapmCStUrjuyUSLk4K/IFkmyn3DZR/X90wkMMOnPohaGyaKIvCv0h3OVllJ0l8bP/9HiesSpe+FlimXawrnmsMvN0az9oalUIBrZRqhCeD6ZzgnbacC306Jteeg0S70/yH1vtVddTprQ6+Q0BdSzqymaXUq2/0X1sF2woNej6MS9BaimfKPLQ2wV4TW9sUME/q71upcLdGix/X1mHT51cWn7EH/xFovCrLFJG+5Wt+goPrykTg3AfPh5MQisHnGw/LvjRqrf7SqmDD5w/pK2WLxWQVa8qBB+uwZhUVoDwSj6o+gIPZwQtEQIasBlYZK4UE2fOm34QFmcksU7y46SoW/1LEUrmgQjE1LfZieP6dim5UwyGghlfAt43Nhk+15ykmKKTNdHxRm0QGKeqvJ4A/NVVhUuS16AXSUoqBZ1MTlV92swHquimcxaNsBeMh6lnacRpxufg+ZCCrwtxJvPs5FlFba8dRBSDtUlzZ33GXTteAvrqWld4zKEUdYuCqH8dTKD1ajVHwgavWBsETT+4Dy+nAAHB9TG8DxGeU9blPh1m4m927WjSeRJzY36NbCYbQ/9LUtOV8/Lg8ZEb7ACnY9OPPyDgj90wsVXbaAl/utv2heFb2JuldIHkbjVt9ixJmLAdtsshnuq36fh6GVkkoLVV99BXAspsB/KnoMuRzDVexVAl1pLTVkhtGuvowzzXH9dT6cG4kzeN4xtE2l60YNvwWy2Kyr0Bm+sasH5WV5i6dF2whuVdCUjGrlQ0HetRKkbzbcXjkj63uICxxIA4CVl+Zb6GfduKwEET1Ik/StwovZc7Aa3SFJOzcT19MhzWIwbQ/hIm2DMnEEpNE1bLfwKMl9EQCmfncPs16WLbdgwA43rj8h6m0R6GHhAAoX1U5lIFycykPyrp7LtMsl2+69HwRvuCB5h2peHCdp4CkShG90ngaqmjvLcQTXDdqzMiqjObcz2uzLzoqLlItKInldy5J

