apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: team-backend-api-stg
  namespace: stg
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:stg-*
spec:
  releaseName: team-backend-api-stg
  chart:
    git: git@github.com:Morriz/mostack
    path: charts/api
    ref: master
  valueFileSecrets:
  - name: api-secrets
  values:
    image:
      tag: stg-e50be0170a6b8caa35a1229f9fcaf232b60220b3