apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-agent
spec:
  replicas: 1
  template:
    metadata:
      annotations:
{{ toYaml .Values.agent.annotations | indent 8 }}
      labels:
        app: {{ .Chart.Name }}
        component: agent
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - name: {{ template "fullname" . }}-agent
        image: drone/agent:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - "server"
        env:
        - name: DRONE_SERVER
          value: {{ template "fullname" . }}:9000
        - name: DRONE_HEALTHCHECK
          value: 'true'
        # issue: https://github.com/drone/drone/issues/2048
        - name: DOCKER_API_VERSION
          value: '1.24'
        - name: DRONE_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: secret
        {{ range $key, $value := .Values.agent.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{ end }}
        resources:
{{ toYaml .Values.agent.resources | indent 10 }}
        volumeMounts:
        # Enables Docker in Docker
        - mountPath: /var/run/docker.sock
          name: docker-socket
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
