apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ .Chart.Name }}
    component: server
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.http.externalPort }}
    targetPort: {{ .Values.service.http.internalPort }}
  - name: grpc
    port: {{ .Values.service.grpc.externalPort }}
    targetPort: {{ .Values.service.grpc.internalPort }}
  selector:
    app: {{ .Chart.Name }}
    component: server
