rbac:
  create: true
controller:
  config:
    ssl-redirect: "true"
    hsts: "true"
    disable-ipv6: "true"
  stats:
    enabled: true
  hostNetwork: true
  service:
    type: {{NGINX_SERVICE_TYPE}}
    loadBalancerIP: {{LOAD_BALANCER_IP}}
    nodePorts:
      http: 32080
      https: 32443

  # resources:
  #    limits:
  #      cpu: 100m
  #      memory: 64Mi
  #    requests:
  #      cpu: 100m
  #      memory: 64Mi
