rbac:
  create: true
controller:
  config:
    ssl-redirect: "true"
    hsts: "true"
    disable-ipv6: "true"
  stats:
    enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  hostNetwork: true
  service:
    type: LoadBalancer
    loadBalancerIP: {{LOAD_BALANCER_IP}}

  # resources:
  #    limits:
  #      cpu: 100m
  #      memory: 64Mi
  #    requests:
  #      cpu: 100m
  #      memory: 64Mi
