rbac:
  create: true
controller:
  extraArgs:
    v: 3
  config:
    ssl-redirect: "true"
    hsts: "true"
    disable-ipv6: "true"
  stats:
    enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels: # needed to be picked up by our one and only prometheus-operator:
        release: prometheus-operator
  # hostNetwork: true
  service:
    type: LoadBalancer
    # type: NodePort
    # nodePorts:
    #   http: 32080
    #   https: 32443
    loadBalancerIP: {{LOAD_BALANCER_IP}}

  # resources:
  #    limits:
  #      cpu: 100m
  #      memory: 64Mi
  #    requests:
  #      cpu: 100m
  #      memory: 64Mi
